# Generated by Django 5.1.6 on 2025-03-09 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_bowlers', models.IntegerField()),
                ('num_batsmen', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_batsmen', models.IntegerField(default=0)),
                ('num_bowlers', models.IntegerField(default=0)),
                ('num_allrounders', models.IntegerField(default=0)),
                ('unique_link', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('batting_high_score', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('economy_rate', models.FloatField(default=0.0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.team')),
            ],
        ),
    ]
