# Generated by Django 5.1.6 on 2025-03-09 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='num_batsmen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creator',
            name='num_bowlers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_allrounders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_batsmen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_bowlers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='unique_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
