# Generated by Django 5.1.6 on 2025-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_creator_num_batsmen_alter_creator_num_bowlers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='num_allrounders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_batsmen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_bowlers',
            field=models.IntegerField(default=0),
        ),
    ]
